<?php
require_once("Pessoa.php");
require_once ("Livro.php");

class Usuario extends Pessoa
{
    private $livrosEmprestados;
    /**
     * @param string $nome
     * @param string $username
     * @param int $id
     */
    public function __construct(string $nome, string $username, int $id)
    {
        parent::__construct($nome, $username, $id);
        $this->livrosEmprestados = array();
    }

    public function getLivrosEmprestados(): array
    {
        return $this->livrosEmprestados;
    }

    public function getNome() : string
    {
        return parent::getNome(); // TODO: Change the autogenerated stub
    }

    public function getUsername(): string
    {
        return parent::getUsername(); // TODO: Change the autogenerated stub
    }

    public function adicionaEmprestado(Livro $livro, $conn){
        database::insertEmprestimo($livro, $this, $conn);
    }

}